### ISSUE TITLE
Connect Failed

### ISSUE THREAD

**Issue by kangozidev** [AliDehbansiahkarbon/ChatGPTExtensionForLazarus#1]
Thanks For Your Code

I Can install to Lazarus IDE ( 2.2.4 ) / FPC 3.2.2 , But still not working because 
show message in Answer
Connect to api.openai.com:443 failed.
when I input ask a question 

I try open port 443 in Firewall (inbound/outbound)  but still not help

**Comment by AliDehbansiahkarbon** [comment]
Actually, connection problems are not something that I can fix it here.
This plug-in is using the built-in HTTP client library (fphttpclient).
I made some changes to the code structure to get a more accurate exception message, please get the latest version and try again, I hope you will get a better exception with more detail.

Put more details here next time:
1- Exception message.
2- OS and version of OS
3- Lazarus version
4- Freepascal version

On a side note, you can ask your questions about Lazarus and Free Pascal in this Lazarus active Telegram group too, they will help:  https://t.me/freepascal_en

**Comment by kangozidev** [comment]
Its Debugger Exception Notification :

Project  raised exception class EScoketError with message
Connect to api.openai.com:443 failed

At address 620B31


I Use Lazarus 2.2.4 ( Win 32 ) / FPC 3.2.2
Windows 10 ( 64 )

**Comment by kangozidev** [comment]
I try compile its in 64Bit

The Notification has change to
"Could not initialize OpenSSL library"

I Add **opensslsocket** at lpr file

```
uses
  {$IFDEF UNIX}
  cthreads,
  {$ENDIF}
  {$IFDEF HASAMIGA}
  athreads,
  {$ENDIF}
  Interfaces, // this includes the LCL widgetset
  Forms, opensslsockets, runtime, typeinfocontrols, lzchatgptwizard, UConsts, UFrame_Question,
  Umain, UQuestion, USetting, UThread
  { you can add units after this };

{$R *.res}        

```

I add some file openssl from **https://indy.fulgan.com/SSL/openssl-1.0.2q-x64_86-win64.zip**  its work ( No Error Again )
But The Answer is blank .. 

I try register new API Key

And Successs ...  

 Use https://indy.fulgan.com/SSL/openssl-1.0.2q-i386-win32.zip to 32bit version ...

Both Successfully
